services:

  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=mk-1
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_c_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service-a:
    build: ./service_a
    depends_on:
      - kafka
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/service-a-db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICE_B_URL: http://service-b:8080
    ports:
      - "8081:8080"

  service-b:
    build: ./service_b
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVICE_C_URL: http://service-c:8080
    ports:
      - "8082:8080"

  service-c:
    build: ./service_c
    depends_on:
      - postgres
      - kafka
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/service_c_db
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8080"

volumes:
  kafka_data:
  mongo_data:
  redis_data:
  postgres_data:
