spring:
  application:
    name: service_b

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

#  data:

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging:
  level:
    root: INFO
    mentorship.roadmap.microservices.service_a: DEBUG
    org.springframework.web: WARN

service-c:
  uri: ${SERVICE_C_URL}